{% set name = "rstcheck" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4b035300b7d898403544f38c3a4980171ce85f487d25e188347bbafb6ee58c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rstcheck = rstcheck:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docutils >=0.7
    - pip

test:
  imports:
    - rstcheck
  commands:
    - python -m rstcheck --help
    - pip check

about:
  home: https://pypi.org/project/rstcheck
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: https://pypi.org/project/rstcheck
  dev_url: https://github.com/myint/rstcheck

extra:
  recipe-maintainers:
    - kynan
