{% set name = "rstcheck" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f656cb2097c4559af13ed4861e68f2190497531cbcaa4d96e994c0591131fa1e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rstcheck = rstcheck:main

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - docutils >=0.7
    - pip
    - types-docutils
    - typing-extensions

test:
  imports:
    - rstcheck
  commands:
    - rstcheck --help
    - pip check

about:
  home: https://pypi.org/project/rstcheck
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: https://pypi.org/project/rstcheck
  dev_url: https://github.com/myint/rstcheck

extra:
  recipe-maintainers:
    - kynan
